[pytest]
# Liste des dossiers à ignorer lors de la collecte des tests
#norecursedirs = infrastructure/mlx_CLXV
# Optionnel : Tu peux aussi forcer pytest à ne chercher que dans ton dossier tests
testpaths = tests